"""message=add forum message file attachment columns

Revision ID: ef25eadc107b
Revises: e1f2a3b4c5d6
Create Date: 2026-08-31 11:10:11.242914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef25eadc107b'
down_revision = 'e1f2a3b4c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('r2_key', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('file_mime_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_message', schema=None) as batch_op:
        batch_op.drop_column('original_filename')
        batch_op.drop_column('file_mime_type')
        batch_op.drop_column('r2_key')

    # ### end Alembic commands ###
