"""add email_verified to user

Revision ID: 0ef86a48e325
Revises: f237e2aa3f54
Create Date: 2026-07-23 11:37:56.647503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef86a48e325'
down_revision = 'f237e2aa3f54'
branch_labels = None
depends_on = None


user = sa.table('user', sa.column('email_verified', sa.Boolean))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###

    # Data migration: every account that exists at this point predates self-service
    # signup with email verification (created via Google OAuth or by an admin), so
    # treat them as already verified. Only new self-service signups start unverified.
    op.get_bind().execute(sa.update(user).values(email_verified=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
