"""message=Add ContentView model for tracking content viewing time

Revision ID: 63af7e9b99c4
Revises: c2f4b6a8d9e1
Create Date: 2026-05-16 17:10:04.291775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63af7e9b99c4'
down_revision = 'c2f4b6a8d9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: The columns being dropped here don't exist in the current schema
    # (services_title, services_subtitle, page_show_title, page_show_description)
    # They were never added, so we skip the drop commands.
    # These columns will be added/managed by later migrations.
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services_title', sa.VARCHAR(length=200), server_default=sa.text("'Our Services'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('services_subtitle', sa.VARCHAR(length=500), server_default=sa.text("'Explore the comprehensive services we offer.'::character varying"), autoincrement=False, nullable=True))

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_show_title', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('page_show_description', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
