"""add about_gallery_2 columns to home_content

Revision ID: 590513ed760f
Revises: remove_about_features_20260524
Create Date: 2026-05-25 11:10:18.548307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590513ed760f'
down_revision = 'b8f6c2e3a051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('page_show_description')
        batch_op.drop_column('page_show_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_show_title', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('page_show_description', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
