"""drop site configurability tables and columns

Revision ID: f237e2aa3f54
Revises: 20260626_content_downloadable
Create Date: 2026-07-22 10:34:36.120028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f237e2aa3f54'
down_revision = '20260626_content_downloadable'
branch_labels = None
depends_on = None


def upgrade():
    # Clean up orphaned translation cache rows for the removed home_content/gallery_item content types
    content_translation = sa.table(
        'content_translation',
        sa.column('content_type', sa.String),
    )
    op.get_bind().execute(
        sa.delete(content_translation).where(
            content_translation.c.content_type.in_(['home_content', 'gallery_item'])
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_logo_url', sa.String(length=500), nullable=True),
    sa.Column('site_name', sa.String(length=200), nullable=True),
    sa.Column('contact_info', sa.JSON(), nullable=True),
    sa.Column('navigation_items', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('page_limitation')
    op.drop_table('home_content')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('page_show_navigation')
        batch_op.drop_column('page_show_title')
        batch_op.drop_column('page_show_footer')
        batch_op.drop_column('page_builder_data')
        batch_op.drop_column('page_show_description')
        batch_op.drop_column('page_welcome_title')
        batch_op.drop_column('page_gallery_images')
        batch_op.drop_column('page_subtitle')
        batch_op.drop_column('dropdown_menu')
        batch_op.drop_column('page_features')
        batch_op.drop_column('page_description')

    with op.batch_alter_table('course_content', schema=None) as batch_op:
        batch_op.alter_column('is_imported',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('pdf_document', schema=None) as batch_op:
        batch_op.alter_column('is_imported',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.alter_column('is_imported',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.alter_column('is_imported',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('pdf_document', schema=None) as batch_op:
        batch_op.alter_column('is_imported',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('course_content', schema=None) as batch_op:
        batch_op.alter_column('is_imported',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('page_features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dropdown_menu', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('page_subtitle', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('page_gallery_images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('page_welcome_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('page_show_description', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('page_builder_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('page_show_footer', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('page_show_title', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('page_show_navigation', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.create_table('home_content',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('welcome_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('subtitle', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('get_started_text', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('logged_out_welcome_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('logged_out_subtitle', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('logged_out_get_started_text', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('logged_out_features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('gallery_images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('courses_section_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('courses_section_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('forum_section_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('forum_section_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resources_section_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('resources_section_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tavi_test_section_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('tavi_test_section_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contact_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('about_section_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('about_section_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('about_welcome_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('about_subtitle', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('features_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('features_subtitle', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('about_gallery_images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('about_gallery_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('about_gallery_subtitle', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('site_logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('site_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('navigation_items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('services_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('services_subtitle', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('about_gallery_2_images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('about_gallery_2_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('about_gallery_2_subtitle', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('home_content_pkey'))
    )
    op.create_table('page_limitation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('page_key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('page_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_limited', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('page_limitation_pkey')),
    sa.UniqueConstraint('page_key', name=op.f('page_limitation_page_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('site_settings')
    # ### end Alembic commands ###
