"""add data column to background_job

Revision ID: fd24307ab3c6
Revises: 1c241dd4b663
Create Date: 2026-07-27 15:00:46.008077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd24307ab3c6'
down_revision = '1c241dd4b663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_job', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
