"""message=content_view.content_id String column type

Revision ID: f2c5eb172d67
Revises: 8a9b0c1d2e3f
Create Date: 2026-05-16 17:26:05.417488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2c5eb172d67'
down_revision = '8a9b0c1d2e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_view', schema=None) as batch_op:
        batch_op.alter_column('viewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('services_subtitle', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.drop_column('services_subtitle')
        batch_op.drop_column('services_title')

    with op.batch_alter_table('content_view', schema=None) as batch_op:
        batch_op.alter_column('viewed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###
