"""message=Restore missing page_show_title and page_show_description columns on Course

Revision ID: 8c30863f44c2
Revises: remove_about_features_20260524
Create Date: 2026-05-25 09:56:07.653375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c30863f44c2'
down_revision = 'remove_about_features_20260524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_features', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('about_features_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('about_features_subtitle', sa.String(length=500), nullable=True))
        batch_op.drop_column('about_gallery_2_subtitle')
        batch_op.drop_column('about_gallery_2_images')
        batch_op.drop_column('about_gallery_2_title')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_show_title', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('page_show_description', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_gallery_2_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('about_gallery_2_images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('about_gallery_2_subtitle', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('about_features_subtitle')
        batch_op.drop_column('about_features_title')
        batch_op.drop_column('about_features')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('page_show_description')
        batch_op.drop_column('page_show_title')

    # ### end Alembic commands ###
