"""add pgvector extension and content embedding table

Revision ID: 3c01ba20a676
Revises: fd24307ab3c6
Create Date: 2026-07-28 11:10:16.121042

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '3c01ba20a676'
down_revision = 'fd24307ab3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('content_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_content_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_content_id'], ['course_content.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_content_id', 'chunk_index', name='uq_content_embedding_chunk')
    )
    with op.batch_alter_table('course_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_content', schema=None) as batch_op:
        batch_op.drop_column('embedded_at')

    op.drop_table('content_embedding')
    # ### end Alembic commands ###
    op.execute('DROP EXTENSION IF EXISTS vector')
