"""add enrollment and promo_code models, is_public flags

Revision ID: 881d4f161cbc
Revises: 0ef86a48e325
Create Date: 2026-07-24 10:26:45.531546

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '881d4f161cbc'
down_revision = '0ef86a48e325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issued_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('joined_via', sa.String(length=30), server_default='direct_add', nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('promo_code_id', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_code.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_enrollment_user_course')
    )
    # Backfill existing user_courses rows as direct_add enrollments before dropping the old table
    user_courses = sa.table('user_courses',
        sa.column('user_id', sa.Integer),
        sa.column('course_id', sa.Integer),
    )
    enrollment = sa.table('enrollment',
        sa.column('user_id', sa.Integer),
        sa.column('course_id', sa.Integer),
        sa.column('joined_via', sa.String),
        sa.column('enrolled_at', sa.DateTime),
    )
    conn = op.get_bind()
    existing_rows = conn.execute(sa.select(user_courses.c.user_id, user_courses.c.course_id)).fetchall()
    if existing_rows:
        now = datetime.utcnow()
        conn.execute(
            sa.insert(enrollment),
            [{'user_id': row.user_id, 'course_id': row.course_id, 'joined_via': 'direct_add', 'enrolled_at': now}
             for row in existing_rows]
        )

    op.drop_table('user_courses')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('forum_channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_channel', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    op.create_table('user_courses',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('user_courses_course_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_courses_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'course_id', name=op.f('user_courses_pkey'))
    )
    op.drop_table('enrollment')
    op.drop_table('promo_code')
    # ### end Alembic commands ###
