"""replace global User.is_teacher with per-course Enrollment.is_teacher

Revision ID: 1c241dd4b663
Revises: fb167026a544
Create Date: 2026-07-24 15:43:40.820691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c241dd4b663'
down_revision = 'fb167026a544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_teacher', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_teacher')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_teacher', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_column('is_teacher')

    # ### end Alembic commands ###
