"""initial

Revision ID: b9b29e2f764f
Revises: 
Create Date: 2026-03-17 00:27:23.289530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b29e2f764f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('background_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('source_language', sa.String(length=10), nullable=True),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_translation', schema=None) as batch_op:
        batch_op.create_index('idx_content_translation_lookup', ['content_type', 'content_id', 'field_name', 'target_language'], unique=False)

    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('time_slot', sa.String(length=100), nullable=True),
    sa.Column('profile_emoji', sa.String(length=10), nullable=True),
    sa.Column('dropdown_menu', sa.JSON(), nullable=True),
    sa.Column('page_welcome_title', sa.String(length=200), nullable=True),
    sa.Column('page_subtitle', sa.String(length=500), nullable=True),
    sa.Column('page_description', sa.Text(), nullable=True),
    sa.Column('page_builder_data', sa.JSON(), nullable=True),
    sa.Column('page_features', sa.JSON(), nullable=True),
    sa.Column('page_gallery_images', sa.JSON(), nullable=True),
    sa.Column('page_show_navigation', sa.Boolean(), nullable=True),
    sa.Column('page_show_footer', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('tab_content_label', sa.String(length=50), nullable=True),
    sa.Column('tab_announcements_label', sa.String(length=50), nullable=True),
    sa.Column('tab_reviews_label', sa.String(length=50), nullable=True),
    sa.Column('tab_assignments_label', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requires_login', sa.Boolean(), nullable=True),
    sa.Column('admin_only', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('home_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('welcome_title', sa.String(length=200), nullable=True),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('get_started_text', sa.String(length=200), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('logged_out_welcome_title', sa.String(length=200), nullable=True),
    sa.Column('logged_out_subtitle', sa.String(length=500), nullable=True),
    sa.Column('logged_out_get_started_text', sa.String(length=200), nullable=True),
    sa.Column('logged_out_features', sa.JSON(), nullable=True),
    sa.Column('gallery_images', sa.JSON(), nullable=True),
    sa.Column('courses_section_title', sa.String(length=200), nullable=True),
    sa.Column('courses_section_description', sa.Text(), nullable=True),
    sa.Column('forum_section_title', sa.String(length=200), nullable=True),
    sa.Column('forum_section_description', sa.Text(), nullable=True),
    sa.Column('resources_section_title', sa.String(length=200), nullable=True),
    sa.Column('resources_section_description', sa.Text(), nullable=True),
    sa.Column('tavi_test_section_title', sa.String(length=200), nullable=True),
    sa.Column('tavi_test_section_description', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.JSON(), nullable=True),
    sa.Column('about_section_title', sa.String(length=200), nullable=True),
    sa.Column('about_section_description', sa.Text(), nullable=True),
    sa.Column('about_welcome_title', sa.String(length=200), nullable=True),
    sa.Column('about_subtitle', sa.Text(), nullable=True),
    sa.Column('about_features', sa.JSON(), nullable=True),
    sa.Column('about_features_title', sa.String(length=200), nullable=True),
    sa.Column('about_features_subtitle', sa.String(length=500), nullable=True),
    sa.Column('features_title', sa.String(length=200), nullable=True),
    sa.Column('features_subtitle', sa.String(length=500), nullable=True),
    sa.Column('about_gallery_images', sa.JSON(), nullable=True),
    sa.Column('about_gallery_title', sa.String(length=200), nullable=True),
    sa.Column('about_gallery_subtitle', sa.String(length=500), nullable=True),
    sa.Column('site_logo_url', sa.String(length=500), nullable=True),
    sa.Column('site_name', sa.String(length=200), nullable=True),
    sa.Column('navigation_items', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('source_language', sa.String(length=10), nullable=True),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('translation_service', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.create_index('idx_translation_lookup', ['source_text', 'target_language'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_teacher', sa.Boolean(), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('google_access_token', sa.Text(), nullable=True),
    sa.Column('google_refresh_token', sa.Text(), nullable=True),
    sa.Column('google_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=True),
    sa.Column('last_attempt_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('course_announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['forum_message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdf_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('drive_file_id', sa.String(length=100), nullable=True),
    sa.Column('drive_view_link', sa.String(length=300), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('access_pin', sa.String(length=10), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('allow_others_to_view', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('preview_image', sa.String(length=300), nullable=True),
    sa.Column('preview_drive_file_id', sa.String(length=100), nullable=True),
    sa.Column('preview_drive_view_link', sa.String(length=300), nullable=True),
    sa.Column('drive_file_id', sa.String(length=100), nullable=True),
    sa.Column('drive_view_link', sa.String(length=300), nullable=True),
    sa.Column('is_image_file', sa.Boolean(), nullable=True),
    sa.Column('access_pin', sa.String(length=10), nullable=True),
    sa.Column('pin_expires_at', sa.DateTime(), nullable=True),
    sa.Column('pin_last_reset', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('allow_others_to_view', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tavi_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_courses',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    op.create_table('course_announcement_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_reply_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['course_announcement.id'], ),
    sa.ForeignKeyConstraint(['parent_reply_id'], ['course_announcement_reply.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_assignment_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=300), nullable=True),
    sa.Column('drive_file_id', sa.String(length=100), nullable=True),
    sa.Column('drive_view_link', sa.String(length=300), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('allow_others_to_view', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['course_assignment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_content_folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('parent_folder_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('locked_until_assignment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['locked_until_assignment_id'], ['course_assignment.id'], ),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['course_content_folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_resource_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'resource_id')
    )
    op.create_table('course_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('content_data', sa.Text(), nullable=True),
    sa.Column('drive_file_id', sa.String(length=100), nullable=True),
    sa.Column('drive_view_link', sa.String(length=300), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('allow_others_to_view', sa.Boolean(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['course_content_folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_content')
    op.drop_table('user_resource_access')
    op.drop_table('course_content_folder')
    op.drop_table('course_assignment_submission')
    op.drop_table('course_announcement_reply')
    op.drop_table('user_courses')
    op.drop_table('tavi_test')
    op.drop_table('resource')
    op.drop_table('pdf_document')
    op.drop_table('forum_message')
    op.drop_table('course_review')
    op.drop_table('course_assignment')
    op.drop_table('course_announcement')
    op.drop_table('user')
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.drop_index('idx_translation_lookup')

    op.drop_table('translation')
    op.drop_table('home_content')
    op.drop_table('forum_channel')
    op.drop_table('course')
    with op.batch_alter_table('content_translation', schema=None) as batch_op:
        batch_op.drop_index('idx_content_translation_lookup')

    op.drop_table('content_translation')
    op.drop_table('background_job')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
