"""fix content_view.content_id column type from Integer to String

Revision ID: 20260518_1506_fix_content_view_content_id_type
Revises: f2c5eb172d67
Create Date: 2026-05-18 15:06:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3a1b2d40518'
down_revision = 'f2c5eb172d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_view', schema=None) as batch_op:
        batch_op.alter_column('content_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False,
               postgresql_using='content_id::varchar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_view', schema=None) as batch_op:
        batch_op.alter_column('content_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using='content_id::integer')
    # ### end Alembic commands ###