"""remove standalone Resource model

Revision ID: bda764d236d2
Revises: a1f2c3d4e5f6
Create Date: 2026-07-24 14:36:38.081629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bda764d236d2'
down_revision = 'a1f2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_resource_access')
    op.drop_table('resource')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('preview_image', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('preview_drive_file_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('preview_drive_view_link', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('drive_file_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('drive_view_link', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('is_image_file', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('access_pin', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('pin_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pin_last_reset', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('allow_others_to_view', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_imported', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], name=op.f('resource_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('resource_pkey'))
    )
    op.create_table('user_resource_access',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accessed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name=op.f('user_resource_access_resource_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_resource_access_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'resource_id', name=op.f('user_resource_access_pkey'))
    )
    # ### end Alembic commands ###
