"""Add declined field to CourseAssignmentSubmission

Revision ID: add_declined_field
Revises: b8f6c2e3a051
Create Date: 2026-05-26 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_declined_field'
down_revision = 'b8f6c2e3a051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_assignment_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('declined', sa.Boolean(), nullable=True, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_assignment_submission', schema=None) as batch_op:
        batch_op.drop_column('declined')

    # ### end Alembic commands ###
